name: github checkout

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout.
      uses: actions/checkout@v2

    - name: Install JDK and Gradle.
      uses: actions/setup-java@v1
      with:
        java-version: '20'
        gradle-version: '7.x'

    - name: Project build and test.
      run: |
        ./gradlew clean test

    - name: Save test result.
      run: |
        cat build/reports/tests/test-result/test/*.xml
